/* eslint-disable */
// This file is generated by Contoprix CLI. Do not edit.

export interface HeaderContent {
  id: string;
  logo?: Record<string, unknown> | Record<string, unknown>[];
  header_links?: Record<string, unknown> | Record<string, unknown>[];
  header_buttons?: Record<string, unknown> | Record<string, unknown>[];
}


export interface HeaderActionButtonsComponentSettings {
  button?: Record<string, unknown> | Record<string, unknown>[];
}

export interface HeaderlinkComponentSettings {
  link?: Record<string, unknown> | Record<string, unknown>[];
}

export interface LogoComponentSettings {
  logo_alt?: string;
  logo_image?: string;
}

export interface NavigationLinkComponentSettings {
}

