/* eslint-disable */
// This file is generated by Contoprix CLI. Do not edit.

export interface BlogPostContent {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: string;
  featured_image?: string | null;
  author?: string | null;
  published_at?: string | null;
  reading_minutes?: number | null;
  category?: "engineering" | "product" | "company_news" | "tutorial" | null;
  is_featured?: boolean | null;
  related_posts?: string[] | null;
  cta?: ButtonComponentSettings | null;
  seo?: SeoComponentSettings | null;
}


export interface ButtonComponentSettings {
  label: string;
  url: string;
  style?: "primary" | "secondary" | "outline" | null;
  open_in_new_tab?: boolean | null;
}

export interface CapabilitiesSectionComponentSettings {
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  capability_items?: {
    capability?: CapabilityItemComponentSettings | null;
  }[] | null;
}

export interface CapabilityItemComponentSettings {
  icon?: string | null;
  title: string;
  description?: string | null;
  link_text?: string | null;
  link?: string | null;
  highlight?: boolean | null;
}

export interface HeroBannerComponentSettings {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  callout?: HeroCalloutComponentSettings | null;
}

export interface HeroCalloutComponentSettings {
  callout_icon?: string | null;
  description?: string | null;
}

export interface SeoComponentSettings {
  meta_title?: string | null;
  meta_description?: string | null;
  social_image?: string | null;
}

