/* eslint-disable */
// This file is generated by Contoprix CLI. Do not edit.

export interface ApiGuideContent {
  id: string;
  title: string;
  slug: string;
  summary?: string | null;
  endpoint?: ApiEndpointComponentSettings | null;
  parameters?: ParameterTableComponentSettings | null;
  body?: string | null;
  code_examples?: string[] | null;
}

export interface BlogPostContent {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: string;
  featured_image?: string | null;
  author?: string | null;
  published_at?: string | null;
  reading_minutes?: number | null;
  category?: "engineering" | "product" | "company_news" | "tutorial" | null;
  is_featured?: boolean | null;
  related_posts?: string[] | null;
  cta?: ButtonComponentSettings | null;
  seo?: SeoComponentSettings | null;
}

export interface CodeExampleContent {
  id: string;
  title: string;
  description?: string | null;
  language: "javascript" | "typescript" | "python" | "bash" | "json" | "csharp";
  code: string;
}

export interface ContentPageContent {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  featured_image?: string | null;
  content?: (({ component: "hero_banner" } & HeroBannerComponentSettings) | ({ component: "content_block" } & ContentBlockComponentSettings) | ({ component: "feature_grid" } & FeatureGridComponentSettings) | ({ component: "testimonial_grid" } & TestimonialGridComponentSettings) | ({ component: "cta_banner" } & CtaBannerComponentSettings) | ({ component: "faq_list" } & FaqListComponentSettings) | ({ component: "image_text" } & ImageTextComponentSettings) | ({ component: "stats_grid" } & StatsGridComponentSettings))[] | null;
  seo?: SeoComponentSettings | null;
  published_at?: string | null;
}

export interface DocumentationPageContent {
  id: string;
  title: string;
  slug: string;
  section?: string | null;
  body: string;
  sort_order?: number | null;
  seo?: SeoComponentSettings | null;
}

export interface DocumentationSectionContent {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  icon?: string | null;
  parent_section?: string | null;
  sort_order?: number | null;
}

export interface FaqContent {
  id: string;
  question: string;
  answer: string;
  category?: string | null;
  sort_order?: number | null;
}

export interface FaqCategoryContent {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  icon?: string | null;
}

export interface GlossaryTermContent {
  id: string;
  term: string;
  slug: string;
  definition: string;
  related_terms?: string[] | null;
}

export interface GuideContent {
  id: string;
  title: string;
  slug: string;
  summary?: string | null;
  body: string;
  difficulty?: "beginner" | "intermediate" | "advanced" | null;
  estimated_time?: string | null;
  topics?: string[] | null;
}

export interface OrganizationContent {
  id: string;
  name: string;
  slug: string;
  logo?: string | null;
  description?: string | null;
  website?: string | null;
  industry?: string | null;
  founded_year?: number | null;
  address?: AddressComponentComponentSettings | null;
  contact?: ContactInfoComponentSettings | null;
}

export interface PersonContent {
  id: string;
  full_name: string;
  slug: string;
  job_title?: string | null;
  bio?: string | null;
  photo?: string | null;
  email?: string | null;
  phone?: string | null;
  social_links?: SocialLinksComponentSettings | null;
}

export interface ReferencePageContent {
  id: string;
  title: string;
  slug: string;
  body: string;
  section?: string | null;
}

export interface TestimonialContent {
  id: string;
  quote: string;
  author_name: string;
  author_title?: string | null;
  company?: string | null;
  avatar?: string | null;
  rating?: number | null;
  featured?: boolean | null;
}

export interface TopicContent {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
}

export interface TutorialContent {
  id: string;
  title: string;
  slug: string;
  summary?: string | null;
  featured_image?: string | null;
  steps?: StepsComponentSettings | null;
  difficulty?: "beginner" | "intermediate" | "advanced" | null;
  estimated_time?: string | null;
}


export interface AccordionComponentSettings {
  heading?: string | null;
  items?: AccordionItemComponentSettings[] | null;
  allow_multiple_open?: boolean | null;
}

export interface AccordionItemComponentSettings {
  title: string;
  content?: string | null;
}

export interface AddressComponentComponentSettings {
  street_1: string;
  street_2?: string | null;
  city: string;
  region?: string | null;
  postal_code?: string | null;
  country: string;
}

export interface ApiEndpointComponentSettings {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  description?: string | null;
}

export interface ButtonComponentSettings {
  label: string;
  url: string;
  style?: "primary" | "secondary" | "outline" | null;
  open_in_new_tab?: boolean | null;
}

export interface CalloutComponentSettings {
  type?: "info" | "success" | "warning" | "danger" | null;
  title?: string | null;
  content?: string | null;
}

export interface CanonicalComponentSettings {
  url?: string | null;
}

export interface CapabilitiesSectionComponentSettings {
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  capability_items?: {
    capability?: CapabilityItemComponentSettings | null;
  }[] | null;
}

export interface CapabilityItemComponentSettings {
  icon?: string | null;
  title: string;
  description?: string | null;
  link_text?: string | null;
  link?: string | null;
  highlight?: boolean | null;
}

export interface CardComponentSettings {
  title: string;
  description?: string | null;
  image?: string | null;
  link?: LinkComponentSettings | null;
}

export interface CardGridComponentSettings {
  heading?: string | null;
  cards?: CardComponentSettings[] | null;
  columns?: number | null;
}

export interface CodeBlockComponentSettings {
  code: string;
  language?: "javascript" | "typescript" | "python" | "bash" | "json" | "csharp" | null;
  filename?: string | null;
  show_line_numbers?: boolean | null;
}

export interface ContactInfoComponentSettings {
  address?: AddressComponentComponentSettings | null;
  phones?: PhoneComponentSettings[] | null;
  emails?: EmailComponentSettings[] | null;
  hours?: string | null;
}

export interface ContentBlockComponentSettings {
  heading?: string | null;
  body?: string | null;
  image?: string | null;
  layout?: "stacked" | "side-by-side" | null;
}

export interface CtaBannerComponentSettings {
  heading: string;
  subheading?: string | null;
  button?: ButtonComponentSettings | null;
  background_color?: string | null;
}

export interface DocumentationNavigationComponentSettings {
  items?: MenuItemComponentComponentSettings[] | null;
}

export interface EmailComponentSettings {
  label?: string | null;
  address: string;
}

export interface FaqItemComponentSettings {
  question: string;
  answer: string;
}

export interface FaqListComponentSettings {
  heading?: string | null;
  items?: FaqItemComponentSettings[] | null;
}

export interface FeatureCardComponentSettings {
  title: string;
  description?: string | null;
  icon?: string | null;
  image?: string | null;
  link?: LinkComponentSettings | null;
}

export interface FeatureGridComponentSettings {
  heading?: string | null;
  subheading?: string | null;
  features?: FeatureCardComponentSettings[] | null;
  columns?: number | null;
}

export interface FooterComponentSettings {
  logo?: string | null;
  description?: string | null;
  navigation_columns?: NavigationMenuComponentSettings[] | null;
  social_links?: SocialLinksComponentSettings | null;
  copyright_text?: string | null;
}

export interface HeaderComponentSettings {
  logo?: string | null;
  navigation?: NavigationMenuComponentSettings | null;
  cta?: ButtonComponentSettings | null;
  sticky?: boolean | null;
}

export interface HeroBannerComponentSettings {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  callout?: HeroCalloutComponentSettings | null;
}

export interface HeroCalloutComponentSettings {
  callout_icon?: string | null;
  description?: string | null;
}

export interface ImageTextComponentSettings {
  image: string;
  heading?: string | null;
  body?: string | null;
  cta?: ButtonComponentSettings | null;
}

export interface LinkComponentSettings {
  label: string;
  url: string;
  target?: "_self" | "_blank" | null;
}

export interface MenuItemComponentComponentSettings {
  label: string;
  url?: string | null;
  icon?: string | null;
  children?: MenuItemComponentComponentSettings[] | null;
}

export interface NavigationMenuComponentSettings {
  name?: string | null;
  items?: MenuItemComponentComponentSettings[] | null;
}

export interface NoteComponentSettings {
  content: string;
}

export interface OpenGraphComponentSettings {
  title?: string | null;
  description?: string | null;
  image?: string | null;
  type?: "website" | "article" | "product" | null;
}

export interface ParameterTableComponentSettings {
  parameters?: Record<string, unknown> | null;
}

export interface PhoneComponentSettings {
  label?: string | null;
  number: string;
}

export interface SeoComponentSettings {
  meta_title?: string | null;
  meta_description?: string | null;
  social_image?: string | null;
}

export interface SocialLinkComponentSettings {
  platform: "x" | "linkedin" | "facebook" | "instagram" | "youtube" | "github" | "tiktok";
  url: string;
}

export interface SocialLinksComponentSettings {
  links?: SocialLinkComponentSettings[] | null;
}

export interface StatComponentSettings {
  value: string;
  suffix?: string | null;
  label: string;
  icon?: string | null;
}

export interface StatsGridComponentSettings {
  heading?: string | null;
  stats?: StatComponentSettings[] | null;
  columns?: number | null;
}

export interface StepComponentSettings {
  number?: number | null;
  title: string;
  content?: string | null;
  image?: string | null;
}

export interface StepsComponentSettings {
  heading?: string | null;
  steps?: StepComponentSettings[] | null;
}

export interface StructuredDataComponentSettings {
  schema_type?: string | null;
  data?: Record<string, unknown> | null;
}

export interface TestimonialCardComponentSettings {
  quote: string;
  author_name: string;
  author_title?: string | null;
  avatar?: string | null;
  company_logo?: string | null;
  rating?: number | null;
}

export interface TestimonialGridComponentSettings {
  heading?: string | null;
  testimonials?: TestimonialCardComponentSettings[] | null;
  columns?: number | null;
}

export interface TipComponentSettings {
  content: string;
}

export interface TwitterCardComponentSettings {
  card_type?: "summary" | "summary_large_image" | null;
  title?: string | null;
  description?: string | null;
  image?: string | null;
}

export interface WarningComponentSettings {
  content: string;
}


// --- Manually added ahead of a real import ---
// These 12 types (course_card + 11 more) exist in contoprix-schema-store/components/*.json
// but haven't been imported into THIS tenant's schema yet -- `contoprix pull` correctly
// omitted them above since they're not real here. Kept so the matching React components
// (CourseCard.tsx, ArticleCard.tsx, etc.) keep compiling; delete this block once the schema
// is imported into Admin and a fresh `contoprix pull && contoprix generate` produces the
// real versions instead. `LinkComponentSettings` above (from the real "link" component) is
// reused rather than redeclared.

export interface CourseCardComponentSettings {
  title: string;
  thumbnail?: string | null;
  instructor_name?: string | null;
  instructor_photo?: string | null;
  level?: "beginner" | "intermediate" | "advanced" | null;
  duration?: string | null;
  lesson_count?: number | null;
  rating?: number | null;
  price?: number | null;
  link?: LinkComponentSettings | null;
}

export interface ArticleCardComponentSettings {
  title: string;
  summary?: string | null;
  image?: string | null;
  category?: string | null;
  author_name?: string | null;
  published_at?: string | null;
  link?: LinkComponentSettings | null;
}

export interface CaseStudyCardComponentSettings {
  title: string;
  client_name?: string | null;
  client_logo?: string | null;
  industry?: string | null;
  summary?: string | null;
  image?: string | null;
  link?: LinkComponentSettings | null;
}

export interface ResourceCardComponentSettings {
  title: string;
  description?: string | null;
  thumbnail?: string | null;
  resource_type?: "guide" | "whitepaper" | "template" | "report" | "video" | "dataset" | null;
  gated?: boolean | null;
  link?: LinkComponentSettings | null;
}

export interface DoctorCardComponentSettings {
  name: string;
  photo?: string | null;
  specialty?: string | null;
  credentials?: string | null;
  location?: string | null;
  accepting_new_patients?: boolean | null;
  link?: LinkComponentSettings | null;
}

export interface ServiceCardComponentSettings {
  name: string;
  icon?: string | null;
  image?: string | null;
  description?: string | null;
  category?: string | null;
  link?: LinkComponentSettings | null;
}

export interface ListingCardComponentSettings {
  name: string;
  image?: string | null;
  category?: string | null;
  rating?: number | null;
  location?: string | null;
  link?: LinkComponentSettings | null;
}

export interface WebinarCardComponentSettings {
  title: string;
  thumbnail?: string | null;
  presenter_name?: string | null;
  scheduled_at?: string | null;
  duration_minutes?: number | null;
  status?: "upcoming" | "on_demand" | null;
  link?: LinkComponentSettings | null;
}

export interface NeighborhoodCardComponentSettings {
  name: string;
  image?: string | null;
  description?: string | null;
  property_count?: number | null;
  price_range?: string | null;
  link?: LinkComponentSettings | null;
}

export interface OfferCardComponentSettings {
  title: string;
  description?: string | null;
  discount_percent?: number | null;
  code?: string | null;
  valid_to?: string | null;
  link?: LinkComponentSettings | null;
}

export interface AwardCardComponentSettings {
  title: string;
  image?: string | null;
  issuer?: string | null;
  year?: number | null;
  description?: string | null;
  link?: LinkComponentSettings | null;
}

export interface DocArticleCardComponentSettings {
  title: string;
  summary?: string | null;
  category?: string | null;
  difficulty?: "beginner" | "intermediate" | "advanced" | null;
  estimated_time?: string | null;
  link?: LinkComponentSettings | null;
}

export interface HelpArticleCardComponentSettings {
  title: string;
  excerpt?: string | null;
  category?: string | null;
  icon?: string | null;
  link?: LinkComponentSettings | null;
}
