// This registry is generated by Contoprix CLI. Do not edit manually.
import BlogPostDetail from "./BlogPostDetail";
import BlogPostList from "./BlogPostList";
import Button from "./Button";
import CapabilitiesSection from "./CapabilitiesSection";
import CapabilityItem from "./CapabilityItem";
import ContentList from "./ContentList";
import HeroBanner from "./HeroBanner";
import HeroCallout from "./HeroCallout";
import Seo from "./Seo";

export const components = {
  "blog_post-detail": BlogPostDetail,
  "blog_post-list": BlogPostList,
  "button": Button,
  "capabilities_section": CapabilitiesSection,
  "capability_item": CapabilityItem,
  "content-list": ContentList,
  "hero_banner": HeroBanner,
  "hero_callout": HeroCallout,
  "seo": Seo,
};

export default components;
